/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DataRouteImport } from './routes/data'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as OtherRouteImport } from './routes/other'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as HistoryIdRouteImport } from './routes/history_.$id'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as TicketsIdRouteImport } from './routes/tickets.$id'
import { Route as ProjectsAuthIdRouteImport } from './routes/projects.auth.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const OtherRoute = OtherRouteImport.update({
  id: '/other',
  path: '/other',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIdRoute = HistoryIdRouteImport.update({
  id: '/history_/$id',
  path: '/history/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsIdRoute = TicketsIdRouteImport.update({
  id: '/tickets/$id',
  path: '/tickets/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsAuthIdRoute = ProjectsAuthIdRouteImport.update({
  id: '/projects/auth/$id',
  path: '/projects/auth/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/data': typeof DataRoute
  '/history': typeof HistoryRoute
  '/other': typeof OtherRoute
  '/reports': typeof ReportsRoute
  '/tasks': typeof TasksRoute
  '/history/$id': typeof HistoryIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/tickets/$id': typeof TicketsIdRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/auth/$id': typeof ProjectsAuthIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/data': typeof DataRoute
  '/history': typeof HistoryRoute
  '/other': typeof OtherRoute
  '/reports': typeof ReportsRoute
  '/tasks': typeof TasksRoute
  '/history/$id': typeof HistoryIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/tickets/$id': typeof TicketsIdRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/auth/$id': typeof ProjectsAuthIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/data': typeof DataRoute
  '/history': typeof HistoryRoute
  '/other': typeof OtherRoute
  '/reports': typeof ReportsRoute
  '/tasks': typeof TasksRoute
  '/history_/$id': typeof HistoryIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/tickets/$id': typeof TicketsIdRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/auth/$id': typeof ProjectsAuthIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/data'
    | '/history'
    | '/other'
    | '/reports'
    | '/tasks'
    | '/history/$id'
    | '/projects/$id'
    | '/tickets/$id'
    | '/projects/'
    | '/projects/auth/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/data'
    | '/history'
    | '/other'
    | '/reports'
    | '/tasks'
    | '/history/$id'
    | '/projects/$id'
    | '/tickets/$id'
    | '/projects'
    | '/projects/auth/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/data'
    | '/history'
    | '/other'
    | '/reports'
    | '/tasks'
    | '/history_/$id'
    | '/projects/$id'
    | '/tickets/$id'
    | '/projects/'
    | '/projects/auth/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DataRoute: typeof DataRoute
  HistoryRoute: typeof HistoryRoute
  OtherRoute: typeof OtherRoute
  ReportsRoute: typeof ReportsRoute
  TasksRoute: typeof TasksRoute
  HistoryIdRoute: typeof HistoryIdRoute
  ProjectsIdRoute: typeof ProjectsIdRoute
  TicketsIdRoute: typeof TicketsIdRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ProjectsAuthIdRoute: typeof ProjectsAuthIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/other': {
      id: '/other'
      path: '/other'
      fullPath: '/other'
      preLoaderRoute: typeof OtherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history_/$id': {
      id: '/history_/$id'
      path: '/history/$id'
      fullPath: '/history/$id'
      preLoaderRoute: typeof HistoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/$id': {
      id: '/tickets/$id'
      path: '/tickets/$id'
      fullPath: '/tickets/$id'
      preLoaderRoute: typeof TicketsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/auth/$id': {
      id: '/projects/auth/$id'
      path: '/projects/auth/$id'
      fullPath: '/projects/auth/$id'
      preLoaderRoute: typeof ProjectsAuthIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DataRoute: DataRoute,
  HistoryRoute: HistoryRoute,
  OtherRoute: OtherRoute,
  ReportsRoute: ReportsRoute,
  TasksRoute: TasksRoute,
  HistoryIdRoute: HistoryIdRoute,
  ProjectsIdRoute: ProjectsIdRoute,
  TicketsIdRoute: TicketsIdRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ProjectsAuthIdRoute: ProjectsAuthIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
