/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AssignRolesRouteImport } from './routes/assign-roles'
import { Route as DataRouteImport } from './routes/data'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as OtherRouteImport } from './routes/other'
import { Route as PermissionsRouteImport } from './routes/permissions'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as UserTransferRouteImport } from './routes/user-transfer'
import { Route as UsersRouteImport } from './routes/users'
import { Route as HistoryIdRouteImport } from './routes/history_.$id'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as TicketsIdRouteImport } from './routes/tickets.$id'
import { Route as ProjectsAuthIdRouteImport } from './routes/projects.auth.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignRolesRoute = AssignRolesRouteImport.update({
  id: '/assign-roles',
  path: '/assign-roles',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const OtherRoute = OtherRouteImport.update({
  id: '/other',
  path: '/other',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionsRoute = PermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const UserTransferRoute = UserTransferRouteImport.update({
  id: '/user-transfer',
  path: '/user-transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIdRoute = HistoryIdRouteImport.update({
  id: '/history_/$id',
  path: '/history/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsIdRoute = TicketsIdRouteImport.update({
  id: '/tickets/$id',
  path: '/tickets/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsAuthIdRoute = ProjectsAuthIdRouteImport.update({
  id: '/projects/auth/$id',
  path: '/projects/auth/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assign-roles': typeof AssignRolesRoute
  '/data': typeof DataRoute
  '/history': typeof HistoryRoute
  '/other': typeof OtherRoute
  '/permissions': typeof PermissionsRoute
  '/reports': typeof ReportsRoute
  '/roles': typeof RolesRoute
  '/tasks': typeof TasksRoute
  '/user-transfer': typeof UserTransferRoute
  '/users': typeof UsersRoute
  '/history/$id': typeof HistoryIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/tickets/$id': typeof TicketsIdRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/auth/$id': typeof ProjectsAuthIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assign-roles': typeof AssignRolesRoute
  '/data': typeof DataRoute
  '/history': typeof HistoryRoute
  '/other': typeof OtherRoute
  '/permissions': typeof PermissionsRoute
  '/reports': typeof ReportsRoute
  '/roles': typeof RolesRoute
  '/tasks': typeof TasksRoute
  '/user-transfer': typeof UserTransferRoute
  '/users': typeof UsersRoute
  '/history/$id': typeof HistoryIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/tickets/$id': typeof TicketsIdRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/auth/$id': typeof ProjectsAuthIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assign-roles': typeof AssignRolesRoute
  '/data': typeof DataRoute
  '/history': typeof HistoryRoute
  '/other': typeof OtherRoute
  '/permissions': typeof PermissionsRoute
  '/reports': typeof ReportsRoute
  '/roles': typeof RolesRoute
  '/tasks': typeof TasksRoute
  '/user-transfer': typeof UserTransferRoute
  '/users': typeof UsersRoute
  '/history_/$id': typeof HistoryIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/tickets/$id': typeof TicketsIdRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/auth/$id': typeof ProjectsAuthIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/assign-roles'
    | '/data'
    | '/history'
    | '/other'
    | '/permissions'
    | '/reports'
    | '/roles'
    | '/tasks'
    | '/user-transfer'
    | '/users'
    | '/history/$id'
    | '/projects/$id'
    | '/tickets/$id'
    | '/projects/'
    | '/projects/auth/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/assign-roles'
    | '/data'
    | '/history'
    | '/other'
    | '/permissions'
    | '/reports'
    | '/roles'
    | '/tasks'
    | '/user-transfer'
    | '/users'
    | '/history/$id'
    | '/projects/$id'
    | '/tickets/$id'
    | '/projects'
    | '/projects/auth/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/assign-roles'
    | '/data'
    | '/history'
    | '/other'
    | '/permissions'
    | '/reports'
    | '/roles'
    | '/tasks'
    | '/user-transfer'
    | '/users'
    | '/history_/$id'
    | '/projects/$id'
    | '/tickets/$id'
    | '/projects/'
    | '/projects/auth/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AssignRolesRoute: typeof AssignRolesRoute
  DataRoute: typeof DataRoute
  HistoryRoute: typeof HistoryRoute
  OtherRoute: typeof OtherRoute
  PermissionsRoute: typeof PermissionsRoute
  ReportsRoute: typeof ReportsRoute
  RolesRoute: typeof RolesRoute
  TasksRoute: typeof TasksRoute
  UserTransferRoute: typeof UserTransferRoute
  UsersRoute: typeof UsersRoute
  HistoryIdRoute: typeof HistoryIdRoute
  ProjectsIdRoute: typeof ProjectsIdRoute
  TicketsIdRoute: typeof TicketsIdRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ProjectsAuthIdRoute: typeof ProjectsAuthIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assign-roles': {
      id: '/assign-roles'
      path: '/assign-roles'
      fullPath: '/assign-roles'
      preLoaderRoute: typeof AssignRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/other': {
      id: '/other'
      path: '/other'
      fullPath: '/other'
      preLoaderRoute: typeof OtherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions': {
      id: '/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof PermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-transfer': {
      id: '/user-transfer'
      path: '/user-transfer'
      fullPath: '/user-transfer'
      preLoaderRoute: typeof UserTransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history_/$id': {
      id: '/history_/$id'
      path: '/history/$id'
      fullPath: '/history/$id'
      preLoaderRoute: typeof HistoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/$id': {
      id: '/tickets/$id'
      path: '/tickets/$id'
      fullPath: '/tickets/$id'
      preLoaderRoute: typeof TicketsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/auth/$id': {
      id: '/projects/auth/$id'
      path: '/projects/auth/$id'
      fullPath: '/projects/auth/$id'
      preLoaderRoute: typeof ProjectsAuthIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AssignRolesRoute: AssignRolesRoute,
  DataRoute: DataRoute,
  HistoryRoute: HistoryRoute,
  OtherRoute: OtherRoute,
  PermissionsRoute: PermissionsRoute,
  ReportsRoute: ReportsRoute,
  RolesRoute: RolesRoute,
  TasksRoute: TasksRoute,
  UserTransferRoute: UserTransferRoute,
  UsersRoute: UsersRoute,
  HistoryIdRoute: HistoryIdRoute,
  ProjectsIdRoute: ProjectsIdRoute,
  TicketsIdRoute: TicketsIdRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ProjectsAuthIdRoute: ProjectsAuthIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
